services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO-INITDB_DATABASE: Dental-Clinic

  dentalclinicmanagement:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo-db
      MONGO_PORT: 27017
      MONGO_DB: dentalclinicmanagement